"use client";

import Link from "next/link";
import { useEffect, useRef, useState } from "react";

type Evidence = {
  tool: string;
  result?: unknown;
  error?: string | null;
};

type Prefill = {
  entity_id: string;
  entity_name?: string;
  hypothesis?: string;
  evidence?: Evidence[];
  suggested_actions?: string[];
  confidence?: number;
};

function buildNarrative(prefill: Prefill): string {
  const lines: string[] = [];
  if (prefill.hypothesis) {
    lines.push("[AI investigation hypothesis]");
    lines.push(prefill.hypothesis);
  }
  if (prefill.suggested_actions && prefill.suggested_actions.length > 0) {
    lines.push("");
    lines.push("[Suggested actions]");
    for (const action of prefill.suggested_actions) {
      lines.push(`• ${action}`);
    }
  }
  if (typeof prefill.confidence === "number") {
    lines.push("");
    lines.push(`[Agent confidence] ${(prefill.confidence * 100).toFixed(0)}%`);
  }
  lines.push("");
  lines.push("— Generated by Kestrel agentic investigation. Review and edit before submission.");
  return lines.join("\n");
}

export function PromoteFromInvestigation({
  investigationId,
  entityId,
}: {
  investigationId: string | null;
  entityId: string | null;
}) {
  const [phase, setPhase] = useState<"checking" | "creating" | "error" | "done">(
    "checking",
  );
  const [error, setError] = useState<string>("");
  const firedRef = useRef(false);

  useEffect(() => {
    if (firedRef.current) return;
    firedRef.current = true;

    const run = async () => {
      if (!entityId) {
        setError("Missing entity context — open this page from an entity dossier's AI panel.");
        setPhase("error");
        return;
      }

      let prefill: Prefill | null = null;
      try {
        const raw = sessionStorage.getItem(`kestrel:investigation:${entityId}`);
        if (raw) prefill = JSON.parse(raw) as Prefill;
      } catch {
        // sessionStorage unavailable — proceed with minimal draft.
      }

      if (!prefill) {
        setError(
          "No investigation prefill found in this session. Re-run the AI investigation on the entity dossier and click Promote again.",
        );
        setPhase("error");
        return;
      }

      setPhase("creating");

      const body = {
        reportType: "str",
        subjectName: prefill.entity_name ?? "Subject from AI investigation",
        narrative: buildNarrative(prefill),
        category: "money_laundering",
        metadata: {
          source: "ai_investigation",
          investigation_id: investigationId,
          entity_id: prefill.entity_id,
          confidence: prefill.confidence ?? null,
          suggested_actions: prefill.suggested_actions ?? [],
        },
      };

      try {
        const response = await fetch("/api/str-reports", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify(body),
        });
        const json = (await response.json()) as { report?: { id?: string }; detail?: string };
        if (!response.ok || !json.report?.id) {
          throw new Error(json.detail ?? `Engine returned ${response.status}`);
        }
        try {
          sessionStorage.removeItem(`kestrel:investigation:${entityId}`);
        } catch {
          /* ignore */
        }
        setPhase("done");
        window.location.replace(`/strs/${json.report.id}`);
      } catch (err) {
        setError(err instanceof Error ? err.message : "Failed to create draft.");
        setPhase("error");
      }
    };

    void run();
  }, [entityId, investigationId]);

  return (
    <section className="border border-border">
      <header className="border-b border-border px-6 py-5">
        <p className="font-mono text-[10px] uppercase tracking-[0.28em] text-muted-foreground">
          <span aria-hidden className="mr-2 text-accent">┼</span>
          Promote · STR draft from AI investigation
        </p>
        <h2 className="mt-2 font-mono text-base uppercase tracking-[0.18em] text-foreground">
          {phase === "checking" || phase === "creating"
            ? "Creating draft from AI investigation…"
            : phase === "done"
              ? "Draft created. Opening workspace…"
              : "Could not create draft."}
        </h2>
      </header>

      <div className="space-y-4 px-6 py-6">
        {(phase === "checking" || phase === "creating") && (
          <div className="space-y-2">
            <p className="text-sm text-muted-foreground">
              Kestrel is creating a new STR draft seeded with the agent&apos;s hypothesis,
              suggested actions, and evidence trail. You will land in the editable STR
              workspace in a moment.
            </p>
            <p className="font-mono text-[10px] uppercase tracking-[0.22em] text-muted-foreground">
              {phase === "checking" ? "Reading investigation context…" : "POST /api/str-reports…"}
            </p>
          </div>
        )}

        {phase === "error" && (
          <div className="space-y-3">
            <p className="font-mono text-xs uppercase tracking-[0.18em] text-destructive">
              <span aria-hidden className="mr-2">┼</span>
              ERROR · {error}
            </p>
            <div className="flex gap-3">
              <Link
                href={entityId ? `/investigate/entity/${entityId}` : "/investigate"}
                className="border border-border px-4 py-2 font-mono text-[11px] uppercase tracking-[0.22em] text-foreground hover:bg-foreground hover:text-background"
              >
                Back to dossier
              </Link>
              <Link
                href="/strs"
                className="border border-border px-4 py-2 font-mono text-[11px] uppercase tracking-[0.22em] text-foreground hover:bg-foreground hover:text-background"
              >
                Open STR workspace
              </Link>
            </div>
          </div>
        )}
      </div>
    </section>
  );
}
